### PR TITLE
Prepare to release 3.0.0~beta1

### PR DESCRIPTION
**Pull request by apoikos**
Update the NEWS file and bump the release version.

### CODE REVIEW

**Comment by apoikos** [comment]
Thanks @saschalucas. I'll wait for #1446 as well and update NEWS accordingly before merging this PR.

**Comment by iustin** [comment]
@apoikos - regaring #1446, I haven't seen any reply to my trivial naming comment, so I just went ahead and fixed it myself on that branch. I don't know if we still wait for CLA or not…

**Comment by rbott** [comment]
> Thanks @saschalucas. I'll wait for #1446 as well and update NEWS accordingly before merging this PR.

Sorry, I entirely overlooked this comment :-(

**Comment by apoikos** [comment]
@iustin: I took the liberty and disabled the CLA integration, as well as the relevant branch protections :-)

**Comment by iustin** [comment]
> > Thanks @saschalucas. I'll wait for #1446 as well and update NEWS accordingly before merging this PR.
> 
> Sorry, I entirely overlooked this comment :-(

Which is why it's best practice to not merge other people's merge requests, unless they don't have rights to do it themselves. Removes such potential misunderstandings.

**Comment by iustin** [comment]
> @iustin: I took the liberty and disabled the CLA integration, as well as the relevant branch protections :-)

Yay on the CLA, not sure on the branch protections :)

**Comment by apoikos** [comment]
> > @iustin: I took the liberty and disabled the CLA integration, as well as the relevant branch protections :-)
> 
> Yay on the CLA, not sure on the branch protections :)

It was only the branch protections that said "CLA required", not all branch protections :-)

**Pull request merged**
