### PR TITLE
Test.OpCodes.arbitraryDuration: distribution of values across orders of magnitudes

### PR DESCRIPTION
**Pull request by thielema**
This should reliably reveal formatting inconsistencies in OpTestDelay.Summary.

Optimally the OpTestDelay test fails on all tested distribution.

### CODE REVIEW

**Comment by thielema** [comment]
Great, with the new `arbitraryDuration` random number generator we obtain even more funny inconsistencies:
~~~~
Haskell: 2.0173879770132213e-8
Python: 2.0173879770132213e-08
~~~~

**Comment by thielema** [comment]
Please do not merge this pull request, I will add fixes to the problem in a subsequent commit.

**Comment by thielema** [comment]
Subsumed by https://github.com/ganeti/ganeti/pull/1798.

**Comment by saschalucas** [comment]
I'm closing this in favor of #1798 being merged.

**Pull request closed without merging**
