### PR TITLE
Drop the `xm` toolstack for the Xen hypervisor

### LINKED ISSUE #1611: xen: drop support for `xm` command
Some years ago the Xen project  deprecated and finally dropped the `xm` command and replaced it with the `xl` command. Ganeti contains code for both commands and also defaults to using `xm`, leading to a bad user experience for users of the Xen hypervisor.

We should:
* drop all code/settings/tests related to `xm`
* remove the `xen_cmd` property
* remove all references to `xm` from the documentation

### PR DESCRIPTION
**Pull request by rbott**
This commits drops support for the `xm` toolstack from the Xen hypervisor implementation in Ganeti. It has been deprecated in Xen version 4.1 and finally dropped in 4.5 (around 2016). There is no need for compability any more.

All of the abstractions built into `XenHypervisor` to support two toolstacks have been removed and unit tests have been updated accordingly. 

This fixes #1611

### CODE REVIEW

**Comment by rbott** [comment]
QA Suite for xen-pvm has been triggered [here](https://github.com/ganeti/ganeti/runs/4767456065?check_suite_focus=true)

**Review by saschalucas — APPROVED** [review]
Thanks @rbott for this work. Since this removes the undocumented HV parameter `xen_cmd` it should be removed from the config on upgrade, too? ... and on downgrade set to `xl`. Feel free to add it here or later.

It seems my review is the best we can get ATM. So LGTM.

**Comment by rbott** [comment]
Ahhh yes, I kind of forgot the upgrade/downgrade handling. I'll take care of that and update the PR accordingly.

**Comment by rbott** [comment]
@saschalucas I have added the up/downgrade part and successfully upgraded stable-3.0 to 3.1. However, I could not test the downgrade (yet) as it is broken. It runs the `DowngradeSshKeyParams()` Method and ends up with this error:

> The current Ganeti setup is using non-DSA SSH keys, and versions below 2.16 do not support these. To downgrade, please perform a gnt-cluster renew-crypto using the  --new-ssh-keys and --ssh-key-type=dsa options, generating DSA keys that older versions can also use.

That is probably not what is supposed to happen on downgrading from 3.1 to 3.0 :-) I'll try to look into that as well and see if I can do anything about at (possibly in a different PR or at least in a separate commit). If you or anybody else can add anything to the solution, please feel free to proceed :-)

**Comment by saschalucas** [comment]
> @saschalucas I have added the up/downgrade part and successfully upgraded stable-3.0 to 3.1. However, I could not test the downgrade (yet) as it is broken. It runs the `DowngradeSshKeyParams()` Method and ends up with this error:
>
> ```
> Verifying 3.0 present on all nodes
> ...
> Downgrade failed:
> Removing SSH parameters failed:
> The current Ganeti setup is using non-DSA SSH keys, and versions below 2.16 do not support these. To downgrade, please perform a gnt-cluster renew-crypto using the  --new-ssh-  keys and --ssh-key-type=dsa options, generating DSA keys that older versions can also use.
> ```

What I understand from `tools/cfgupgrade.py` is, that all config upgrades are always applied (idempotent). That's why one can upgrade from i.e. 2.15 to 3.0 like in #1628.

Downgrade is supposed to work for one minor version. Because Ganeti 2.16 and 3.0 use the same config model, I assume that:
* downgrade from 3.0 to 2.16 was never implemented/tested (MAJOR version differ)
* non-DSA SSH keys are introduced with 2.16, which is why the code for downgrade to 2.15 is still present

So I suppose, that for Ganeti-3.1 `DowngradeSshKeyParams()`should be removed from `DowngradeAll()`???

**Comment by rbott** [comment]
> So I suppose, that for Ganeti-3.1 `DowngradeSshKeyParams()`should be removed from `DowngradeAll()`???

Oh boy, you are entirely right. Sorry for not seeing that earlier :-) I will remove the code and test again!

**Comment by rbott** [comment]
I am currently running once more a QA for xen-pvm ([Link](https://github.com/ganeti/ganeti/runs/4827912778?check_suite_focus=true)) and will add one more for xen-hvm after that. Could you take a quick look again @saschalucas? Unless you see anything, I guess we are good to go then.

**Comment by saschalucas** [comment]
> Could you take a quick look again @saschalucas? Unless you see anything, I guess we are good to go then.

Thanks @rbott. Upgrade/Downgrade looks good. Please merge your changes.

**Comment by rbott** [comment]
Did some additional (non-functional) cleanup/added documentation updates. Tests & QA are still fine.

Merging now, thanks @saschalucas for the review & input! :-)

**Pull request merged**
