### PR TITLE
Issue 1180: Ceph/RBD rbd showmapped -p is no longer supported

### PR DESCRIPTION
**Pull request by atta**
in order to solve the missing "-p" option in "rbd showmapped" it is removed from the showmap_cmd.
to make shure we found the volume in the showmapped (json) output, we now check also the pool in the _ParseRbdShowmappedJson method

### CODE REVIEW

**Comment by Morgawr** [comment]
This has been committed "out of band" via mailing list. The patch can be found at https://github.com/ganeti/ganeti/commit/27a999616efefcff96b14688208c93c6a76d8813

I'll be closing this pull request.

**Comment by flokli** [comment]
@Morgawr This still needs to go into the `stable-2.17` and `master` branch, as it's currently broken there, too.

**Comment by flokli** [comment]
@Morgawr should I file PRs for these branches too, or will `stable-2.16` get merged into `stable-2.17` as done in December 2016? Not sure about the branching model used for ganeti…

**Comment by Morgawr** [comment]
I'm planning to do a new merge forward to 2.17 and master, but first I want to get a couple more pull requests merge to 2.16 to minimize the effort. I'll get everything done in the upcoming days.

**Pull request closed without merging**
