### PR TITLE
overworked README

### PR DESCRIPTION
**Pull request by Kloppi313**
Hi there,

I just did collect some information about ganeti in the readme. Despite I renamed it to `README.md` to make it clear as Markdown, so its being rendered properly here.

!Attention:
In the section Getting Started I left the nightly builds as the link is a dead end: https://deb.ganeti.dev/
https://ganeti.org/gettingstarted.html

### CODE REVIEW

**Review by saschalucas — CHANGES_REQUESTED** [review]
Thanks @Kloppi313, please also change references in `Makefile.am` to `README.md`. 

And while at it, fix the version pattern test for non `alpha` versions: https://github.com/ganeti/ganeti/blob/acf5d519478bfc7138c049022c4c79812240644d/Makefile.am#L2614-L2616

That means:
* keep the version in the headline
* fix pattern to include markdown `#`

**Comment by Kloppi313** [comment]
done in latest commit

**Review by codefritzel — APPROVED** [review]
Hi @Kloppi313 ,
looks good to me but can you please squash the commits into one?

**Comment by Kloppi313** [comment]
I guess it happened. I managed to rewrite history in git as expected.

**Review by saschalucas — APPROVED** [review]
Thanks @Kloppi313.

**Pull request merged**
