### PR TITLE
Fix openvswitch port setup when no untagged VLANs are used

### PR DESCRIPTION
**Pull request by gedia**
OpenVSwitch port setup fails when a port is only configured to carry
tagged VLANs, due to the VLAN's configuration string being malformed.
This patch fixes these cases.

Signed-off-by: George Diamantopoulos <gdiamantopoulos@modulus.gr>

### CODE REVIEW

**Comment by gedia** [comment]
I signed it!

**Comment by gedia** [comment]
I signed it!

**Comment by apoikos** [comment]
@gedia, thanks for the PR!

Since we're lacking tests for net-common, could you give an example of a `vlan` string that triggers this bug?

**Comment by gedia** [comment]
Sure:

`nics: "0:link=vswitch0,mode=openvswitch,vlan=:120:1200"`

We use RAPI to create instances, I'm not sure if this also manifests from the command line, although I expect it does.

**Comment by apoikos** [comment]
Thanks! Would you mind including this in the commit message, so that it's clearly visible what this patch tries to achieve? Other than that, LGTM.

**Comment by apoikos** [comment]
@gedia: If you have some time to address the comment, I'd like to merge this in for v2.16.1 (probably early next week). Thanks!

**Comment by gedia** [comment]
Sorry, it's been a hectic past few days.

I've just force-pushed the patch with an amended commit message.

**Pull request merged**
