### PR TITLE
Reset master

### PR DESCRIPTION
**Pull request by iustin**
Merge branch 'master' into stable-2.16
    
"Ours" merge to discard changes on the master branch, in preparation for development reset. See
https://groups.google.com/d/topic/ganeti/P-TBuaO7Mko/discussion for background.

Commands run:

    $ git checkout stable-2.16
    $ git pull
    $ git show
    $ git merge -s ours master
    $ git push --force mine stable-2.16:reset-master

### CODE REVIEW

**Comment by iustin** [comment]
This is only a merge, there are no new commits added to the repository, so the CLA-patches-authored-by-others can and should be ignored.

**Comment by iustin** [comment]
@apoikos - won't that merge be ignored since 2.16 will later do `-s ours` anyway?

**Comment by apoikos** [comment]
Ah, now I noticed that `stable-2.17` is fully merged into master, so no need to merge again.

**Comment by apoikos** [comment]
I confirm both branches point to the same tree:

```
$ git show --no-patch --format=%T iustin/reset-master v2.16.0^{}
d48b6b652f8fedd641755931ee3f096c7f0ade90
d48b6b652f8fedd641755931ee3f096c7f0ade90
```

**Comment by iustin** [comment]
Per conversation in private email:

```shell
$ git show --no-patch --format=%T v2.16.0^{} stable-2.16
d48b6b652f8fedd641755931ee3f096c7f0ade90
d48b6b652f8fedd641755931ee3f096c7f0ade90
```

Where stable-2.16 was my local branch.

**Comment by iustin** [comment]
Will follow the command line merge instructions:

```
git checkout -b iustin-reset-master master
git pull https://github.com/iustin/ganeti.git reset-master
git checkout master
git merge --no-ff iustin-reset-master
git push origin master
```

**Comment by iustin** [comment]
Merged. Will send email to ganeti/ganeti-devel.

**Comment by apoikos** [comment]
Thanks!

**Comment by iustin** [comment]
So `git log` shows that commit ca13c06f439d73cd37db0b3377534a9e962cdf5a has somehow sneaked in. Not sure where i made a mistake, probably merged stable-2.16 and not v2.16.0. But the commit seems harmless, so all goo.

**Comment by apoikos** [comment]
`git log` sorts commits by date, and the commit is there because from git's point of view it's "merged", but if you look at the file, the commit's effect is gone :)

**Comment by apoikos** [comment]
IOW, `git log master..stable-2.16` shows nothing, but `git log --left-right --left-only --cherry-pick master...stable-2.16`¹ will show all commits that whose effect was discarded by the `-s ours` merge.

¹pay attention to the three dots for a symmetric diff.

**Comment by iustin** [comment]
@apoikos: I was not aware about how "no parents before children" and date ordering works, interesting.

For the other command, I don't get the output you suggest. Rather, a delta between attic/master and v2.16.0 is that I need to see the missed commits.

**Pull request merged**
