### PR TITLE
merge stable-2.16 into master (Fix docs by removing sphinx pre-1.3 support)

### PR DESCRIPTION
**Pull request by saschalucas**
PR #1522 is merged into stable-2.16, so merging stable-2.16 into master here, in order to build docs properly.

### CODE REVIEW

**Review by iustin — APPROVED** [review]
thanks!

**Comment by saschalucas** [comment]
rebasing a merge commit seems not trivial to me. some day I'll learn how to do so. for tonight I use the merge button at github.

**Comment by iustin** [comment]
I don't think rebasing merge commits is ever possible. Merge commits are… merges, by definition.

(Also happy to learn I'm wrong, of course)

**Comment by mbakke** [comment]
`git rebase` has a `--rebase-merges` option, which is just as hairy as it sounds.  I've had the questionable honor of actually needing it on a large code base, and it would be nearly impossible if I did not have considerable experience solving difficult merge conflicts on the repo in question (as well as `git rerere` because it took a few tries to get right).

**Pull request merged**
