### PR TITLE
allow three alternative RegEx implementations: regex-pcre, regex-pcre-builtin, regex-tdfa

### PR DESCRIPTION
**Pull request by thielema**
regex-pcre remains the default
Query.RegEx: module providing a uniform interface across RegEx implementations

I still have to find out, how to make a `configure` option for those alternatives.

### CODE REVIEW

**Comment by thielema** [comment]
Build fails at generating `Makefile.ghc` because `ghc -M` needs the `Ganeti.Query.RegEx` and this is in different directories, depending on the selection of `regex-pcre`, `regex-pcre-builtin`, `regex-tdfa`.

It is simpler to fix with the static `ganeti.cabal` in the `cabal-build` branch.

**Comment by saschalucas** [comment]
> It is simpler to fix with the static `ganeti.cabal` in the `cabal-build` branch.

Understood. Will review this soon.

**Comment by saschalucas** [comment]
> It is simpler to fix with the static `ganeti.cabal` in the `cabal-build` branch.

this is merged now.

**Comment by thielema** [comment]
I still have to get `configure.ac` right.

**Comment by thielema** [comment]
try to re-open

**Comment by thielema** [comment]
Please leave the two commits intact.

**Comment by thielema** [comment]
blabla

**Comment by thielema** [comment]
re-open

**Comment by thielema** [comment]
There is now also:
https://hackage.haskell.org/package/regex-pcre2

So in principle we could re-add pcre2 as an option.

**Comment by apoikos** [comment]
Hi @thielema! PCRE2 support has already been implemented with #1832.

**Pull request closed without merging**
