### PR TITLE
Backports fixes from the last months to stable-3.0

### PR DESCRIPTION
**Pull request by rbott**
This backports all kinds of bugfixes from current master to the stable-3.0 branch in preparation of releasing a 3.0.2 version.

### CODE REVIEW

**Comment by rbott** [comment]
BTW we can keep this open until all currently open PRs with "backport-to-3.0" tag have been resolved (either merged or rejected).
Currently these are: #1622, #1614 and #1603

**Comment by saschalucas** [comment]
Thanks @rbott for pushing towards a 3.0.2 release. Two things before my final check:

1. while switching to the backports model, we agreed on @iustin's hint to cherry-pick with `-x` to indicate which commit this change was cherry-picked from. Do I see it right, that this is missing here?
2. there are some open PRs I like to see in 3.0.2, but actually not in this PR:
* #1603 seems very important for working live migration with `security_model=user|pool` **I see no reason for not merging, please review**
* #1614 just a small fix for VLAN-aware bridge users (like me) **works for me :smile:, please review**
* maybe #1622 (but let me double check again what's happening during live migration between a instance started by the unpatched version and live migrated by the patched one).

**Comment by saschalucas** [comment]
>     * maybe [Qemu-Guest-Agent (QGA): use implicit PCI slot #1622](https://github.com/ganeti/ganeti/pull/1622) (but let me double check again what's happening during live migration between a instance started by the unpatched version and live migrated by the patched one).

I've checked it. It's safe for live migration. The QGA pci slot is stable during migration and changed only after reboot with patched Ganeti. Please review #1622, to include it here.

**Comment by rbott** [comment]
Ah yes, I forgot to use `-x` :-( I will fix that asap!

**Comment by saschalucas** [comment]
so next step is #1603, this seems the most anoying bug people struggling with in Bullseye (see ganeti mailing list).

**Comment by saschalucas** [comment]
> so next step is #1603, this seems the most anoying bug people struggling with in Bullseye (see ganeti mailing list).

Just for further explanation: The problem solved in #1603 can not be discovered by testing (single??) live migration, because the migration will succeed. Sadly the instance becomes paused and is frozen. In order to cover this case, i.e. in the QA-suite, additional liveliness probes like ICMP pinging the instance must be done.

**Comment by rbott** [comment]
I have also pulled in #1646, #1647 and #1648

**Comment by rbott** [comment]
So, there's only #1614 left now.

@apoikos if you put on your Debian hat, is there anything that shouldn't go into 3.0 (or which _should_ go into 3.0 but is not yet in this PR)?

**Comment by saschalucas** [comment]
> So, there's only #1614 left now.

It would be no problem, if we decide not to backport it. It's a rare use case, affecting me and @newellz2 in #1533 (more precise I learned from there, how VLAN aware an traditional bridges can coexist within the same VLAN). OTOH VLAN aware bridge support is new in 3.0 and probably not wildly used.

> @apoikos if you put on your Debian hat, is there anything that shouldn't go into 3.0 (or which _should_ go into 3.0 but is not yet in this PR)?

Going through the labels "Backport to 3.0" I can't find #1615, which seems debian related. @apoikos included it in his patches: https://metadata.ftp-master.debian.org/changelogs//main/g/ganeti/ganeti_3.0.1-3_changelog

**Comment by rbott** [comment]
> > So, there's only #1614 left now.
> 
> It would be no problem, if we decide not to backport it. It's a rare use case, affecting me and @newellz2 in #1533 (more precise I learned from there, how VLAN aware an traditional bridges can coexist within the same VLAN). OTOH VLAN aware bridge support is new in 3.0 and probably not wildly used.

If reviewed it and it looks good to me :-) Actually all of our Ganeti 3 clusters use vlan aware bridging now, thanks for that feature!

> 
> Going through the labels "Backport to 3.0" I can't find #1615, which seems debian related.

Oh, that one slipped through. I'll ad it!

**Review by saschalucas — APPROVED** [review]
Thanks @rbott. I have nothing else to add. Please decide on your own, if you want to backport #1614.

Let's make 3.0.2.

**Comment by rbott** [comment]
I ran some tests today (both with the QA suite and manually) and so far everything looks fine, apart from #1649. I am not sure if we should postpone a 3.0.2 release any longer because of that issue. The current workaround would be to try and run the hotplug command again, but it does not break anything essential.

What do you think @saschalucas? If you agree, I will merge this PR and we can prepare a release.

**Comment by saschalucas** [comment]
> What do you think @saschalucas? If you agree, I will merge this PR and we can prepare a release.

I agree with merging this PR. #1649 can be solved later. If you think, Bugfix #1652 should be included, feel free ...

LGTM.

**Comment by rbott** [comment]
@saschalucas could you take a final look again? After that, this PR will be merged at last!

**Review by saschalucas — APPROVED** [review]
Thanks @rbott! Please merge your changes and LGTM.

**Pull request merged**
