### PR TITLE
Full picosecond range

### PR DESCRIPTION
**Pull request by thielema**

### CODE REVIEW

**Comment by thielema** [comment]
please squash the commits, the second one maintains 80-character-width constraint.

**Comment by saschalucas** [comment]
can you give me some context here? does this solve #1778?

**Comment by thielema** [comment]
On Wed, 14 Aug 2024, saschalucas wrote:

> can you give me some context here? does this solve #1778?

I hope that using the full range of admissible picosecond values would 
trigger the failure of timediffAdd more reliably. This would improve the 
strength of the test.

**Comment by thielema** [comment]
Superseeded by https://github.com/ganeti/ganeti/pull/1790.

**Pull request closed without merging**
