### PR TITLE
Adding links in readme to community resources

### PR DESCRIPTION
**Pull request by chandru9279**
I spent a lot of time installing haskell and cabal dependencies for building ganeti from sources in Centos 6.7 using Install instructions of Ganeti docs

When I discovered RPMs were already available - I realized could have saved a lot of time by using it. 

Also the debootstrap link pointing to code.google.com is broken. Since gnt-cluster verify warns that is required if we have guest debian OS I used the debootstrap rpm from the community site, which works well.

### CODE REVIEW

**Comment by chandru9279** [comment]
I signed it!

**Comment by Morgawr** [comment]
Thanks for spotting this, unfortunately after we migrated from code.google.com to github some stuff is still in pending transition and some links may be broken. I appreciate the effort of adding clarity to our documentation.

Ganeti has been generally a "debian" project in the way that we don't really do any testing on centos or use any RPMs officially, so I'm not entirely sure about having direct links to external RPM/centos sites in our readme. Maybe we should point the user to www.ganeti.org website and have those linked there instead as part of community resources?

**Comment by Morgawr** [comment]
Also I'm not sure why the CLA googlebot is complaining again after I updated the branch for the pull request, but we can solve that later.

**Comment by iustin** [comment]
@Morgawr - I think this should be fine to go in the readme, as long as a new paragraph would be added saying explicitly that these (the community resources) are unsupported. What do you think?

**Comment by atta** [comment]
The links are still OK but we will not release ganeti 2.17!
So if we can make shure to have ganeti 3.0.0 rpm-packages at this resources i would be more than happy to add it.

**Comment by rbott** [comment]
I will close this in favor of #1609 1609

**Pull request closed without merging**
