### PR TITLE
netutils: use correct syntax of iproute2 when getting ip address

### PR DESCRIPTION
**Pull request by arnd**
Before this patch there was a bug when the interface name was actually "dev":

2016-10-11 19:45:05,025: ganeti-noded pid=15175 INFO RunCmd /sbin/ip -o addr show dev
2016-10-11 19:45:05,027: ganeti-noded pid=15175 ERROR Error running the ip command while getting the IP addresses of dev
2016-10-11 19:45:05,027: ganeti-noded pid=15175 ERROR Error in RPC call
Traceback (most recent call last):
  File "/usr/share/ganeti/2.12/ganeti/server/noded.py", line 191, in HandleRequest
    result = (True, method(serializer.LoadJson(req.request_body)))
  File "/usr/share/ganeti/2.12/ganeti/server/noded.py", line 627, in perspective_instance_start
    return backend.StartInstance(instance, startup_paused, trail)
  File "/usr/share/ganeti/2.12/ganeti/backend.py", line 1892, in StartInstance
    hyper.StartInstance(instance, block_devices, startup_paused)
  File "/usr/share/ganeti/2.12/ganeti/hypervisor/hv_kvm/**init**.py", line 1775, in StartInstance
    startup_paused, kvmhelp)
  File "/usr/share/ganeti/2.12/ganeti/hypervisor/hv_kvm/**init**.py", line 1269, in _GenerateKVMRuntime
    elif (addresses[constants.IP4_VERSION] and
TypeError: 'NoneType' object has no attribute '__getitem__'

The previous code only worked, because iproute2 is liberate in what it
excepts. However the correct syntax is:
ip address { show | save | flush } [ dev IFNAME ]

This patch fixes the bug by using the correct syntax.

Signed-off-by: Arnd Hannemann arnd@arndnet.de

### CODE REVIEW

**Comment by ge-fa** [comment]
Looks good to me.

**Comment by RafaelMarinheiro** [comment]
Hi there!

Which versions are affected by this? Can we apply this to 2.15?

**Comment by arnd** [comment]
AFAIK, all versions are affected. The patch applies cleanly to 2.15.

**Comment by RafaelMarinheiro** [comment]
Since this change modifies depends on an external package, I'd rather apply that on 2.16. I'll do that and wait for the tests on Travis.

**Comment by arnd** [comment]
Hmm, maybe there is some misunderstanding? It is really only a one line fix.
May change is purely in commit 8f15143137d2de8d37a339616952b05dfbd8c103
It should be safe to cherry-pick that commit for any stable branch.

**Comment by ge-fa** [comment]
Ping..

**Comment by Morgawr** [comment]
LGTM, I'll be merging this. Thanks and apologies for the long wait, it had completely gone under my radar.

**Pull request merged**
